// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prototipos;

#nullable disable

namespace Prototipos.DAL.Migrations
{
    [DbContext(typeof(PrototiposContext))]
    [Migration("20231130093300_Cuenta Tablev2")]
    partial class CuentaTablev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prototipos.DAL.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<string>("ComensalACargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCuentaPadre")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCuentaPadre");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdMesero");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<string>("NombreMesa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Personas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdZona");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoReserva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<string>("PersonaACargo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMesa");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreZona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Cuenta", b =>
                {
                    b.HasOne("Prototipos.DAL.Models.Cuenta", "CuentaPadre")
                        .WithMany("CuentasHijas")
                        .HasForeignKey("IdCuentaPadre");

                    b.HasOne("Prototipos.DAL.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("IdMesa");

                    b.HasOne("Prototipos.DAL.Models.Usuario", "Mesero")
                        .WithMany()
                        .HasForeignKey("IdMesero");

                    b.Navigation("CuentaPadre");

                    b.Navigation("Mesa");

                    b.Navigation("Mesero");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Mesa", b =>
                {
                    b.HasOne("Prototipos.DAL.Models.Zona", "Zona")
                        .WithMany("Mesas")
                        .HasForeignKey("IdZona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Reserva", b =>
                {
                    b.HasOne("Prototipos.DAL.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("IdMesa");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Cuenta", b =>
                {
                    b.Navigation("CuentasHijas");
                });

            modelBuilder.Entity("Prototipos.DAL.Models.Zona", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
